import { requireUser } from "@/lib/session";import { sql } from "@/lib/db";import { BillingButtons,DiscordForm,PrivacyControls } from "@/components/SettingsForms";
export default async function SettingsPage(){
  const user=await requireUser();
  const rows=await sql.unsafe("SELECT p.display_name,p.slug,s.status,s.cadence,s.current_period_end FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.user_id=$1 LIMIT 1",[user.id]);
  const plan=rows[0];
  const priceRows=await sql.unsafe("SELECT p.slug,p.display_name,pp.currency,pp.cadence,pp.amount_minor FROM plan_prices pp JOIN plans p ON p.id=pp.plan_id WHERE pp.active=true AND p.visible=true AND p.archived=false AND p.slug<>'free' ORDER BY p.sort_order,pp.currency,pp.cadence");
  const prices=priceRows.map((p:any)=>({planSlug:String(p.slug),planName:String(p.display_name),currency:String(p.currency),cadence:String(p.cadence) as "MONTHLY"|"ANNUAL",amountMinor:Number(p.amount_minor)}));
  return <><div className="page-title"><div><div className="eyebrow">Settings</div><h1>Account controls</h1><p>Billing, privacy and notification destinations.</p></div></div><div className="detail-grid"><section className="glass form-card"><h3>Plan</h3><p className="help">{plan?.display_name??"Free"} · {plan?.status??"FREE"} · {plan?.cadence??"FREE"}</p><BillingButtons prices={prices} defaultCurrency={user.baseCurrency}/></section><section className="glass form-card"><h3>Discord notifications</h3><p className="help">Investor and Pro can add an encrypted Discord webhook.</p><DiscordForm/></section></div><section className="card" style={{marginTop:16}}><h3>Privacy & account data</h3><p className="help">Public aggregation operates only on privacy-thresholded derived aggregates. Opting out excludes this account from future aggregate generation.</p><PrivacyControls optIn={user.anonymousAggregateOptIn}/></section></>;
}
