import { notFound } from "next/navigation";
import { requireUser } from "@/lib/session";
import { getStrategyForUser } from "@/lib/strategy-service";
import { sql } from "@/lib/db";
import { PerformanceChart } from "@/components/PerformanceChart";
import { ContributionForm, ExecuteAction, OpeningSnapshotForm, RecalculateButton, ReconcileForm, StrategyLifecycleControls } from "@/components/StrategyActions";

export default async function StrategyPage({params}:{params:Promise<{id:string}>}){
  const user=await requireUser();const {id}=await params;const s:any=await getStrategyForUser(user.id,id);if(!s)notFound();
  const actionRows=await sql.unsafe("SELECT id,action_type,status,title,instruction,amount,currency,explanation,confidence,due_at,created_at FROM actions WHERE strategy_instance_id=$1 AND status IN ('CALCULATED','NOTIFIED','ACKNOWLEDGED') ORDER BY created_at DESC LIMIT 1",[id]);
  const action=actionRows[0];
  const performance=await sql.unsafe("SELECT date,series_type,value FROM performance_series WHERE strategy_instance_id=$1 ORDER BY date",[id]);
  const byDate=new Map<string,any>();for(const p of performance){const d=String(p.date).slice(0,10);const item=byDate.get(d)??{date:d};if(p.series_type==="USER_VALUE")item.actual=Number(p.value);if(p.series_type==="MODEL")item.model=Number(p.value);if(p.series_type==="BENCHMARK")item.benchmark=Number(p.value);byDate.set(d,item);}
  const contributions=await sql.unsafe("SELECT occurred_at,cash_amount,provenance,confidence FROM ledger_events WHERE strategy_instance_id=$1 AND event_type='CONTRIBUTION' ORDER BY occurred_at DESC LIMIT 8",[id]);
  const reconciliations=await sql.unsafe("SELECT occurred_at,expected_value,broker_reported_value,difference,reason FROM reconciliations WHERE strategy_instance_id=$1 ORDER BY occurred_at DESC LIMIT 5",[id]);
  const latestValue=performance.filter((p:any)=>p.series_type==="USER_VALUE").at(-1);
  const explanation=Array.isArray(action?.explanation)?action.explanation:[];
  const needsOpeningSnapshot=Boolean(s.state?.resumeNeedsReconciliation);
  return <><div className="page-title"><div><div className="eyebrow">{s.strategy_name} · v{s.version}</div><h1>{s.name}</h1><p>{s.description}</p></div><div className="inline"><span className={"pill "+(s.health_status==="HEALTHY"?"good":"warn")}>{s.health_status.replaceAll("_"," ")}</span>{s.status==="ACTIVE"&&<RecalculateButton id={id}/>}<StrategyLifecycleControls id={id} status={s.status}/></div></div>
  <div className="metrics"><div className="glass metric"><small>Current tracked value</small><strong>{latestValue?new Intl.NumberFormat("en-GB",{style:"currency",currency:s.currency,maximumFractionDigits:0}).format(Number(latestValue.value)):"—"}</strong></div><div className="glass metric"><small>Account</small><strong>{s.wrapper}</strong></div><div className="glass metric"><small>Last reconciliation</small><strong>{s.last_reconciled_at?new Date(s.last_reconciled_at).toLocaleDateString("en-GB"):"Never"}</strong></div><div className="glass metric"><small>Data confidence</small><strong>{action?.confidence??"—"}</strong></div></div>
  <div className="detail-grid"><section className="glass action-card"><div className={"pill "+(action?.confidence==="HIGH"?"good":"warn")}>NEXT ACTION</div><h2>{action?.title??"No calculated action"}</h2><p>{action?.instruction??"Recalculate when your ledger and market data are ready."}</p>{explanation.length>0&&<div className="why"><div className="eyebrow">Why?</div>{explanation.map((row:any,i:number)=><div className="why-row" key={i}><span>{row.label}</span><b>{row.value}</b></div>)}</div>}{action&&action.action_type!=="DATA_REQUIRED"&&action.action_type!=="NO_ACTION"&&<div style={{marginTop:18}}><ExecuteAction action={{id:String(action.id),actionType:String(action.action_type)}}/></div>}</section>
  <section className="glass form-card"><div className="eyebrow">Strategy health</div><h3>{s.health_status==="HEALTHY"?"Healthy":"Needs attention"}</h3><p className="help">A high-confidence financial action is suppressed whenever critical holdings or market data are stale, missing or unresolved.</p><div className="strategy-meta"><span className="pill">Version {s.version}</span><span className="pill">{s.currency}</span><span className="pill">{s.onboarding_mode.replaceAll("_"," ")}</span></div></section></div>
  {needsOpeningSnapshot&&<section className="glass form-card" style={{marginTop:16}}><div className="eyebrow">Quick Resume</div><h3>Enter your current holdings snapshot</h3><p className="help">Actions remain blocked until the current cash and holdings are recorded.</p><OpeningSnapshotForm id={id}/></section>}
  <section className="glass chart-card"><div className="section-head"><div><h2>Performance</h2><p>Actual implementation, canonical model and benchmark remain distinct series.</p></div></div><PerformanceChart data={[...byDate.values()]}/></section>
  <div className="detail-grid"><section className="glass form-card"><h3>Record contribution</h3><p className="help">A contribution is cash first. It does not imply a security purchase.</p><ContributionForm id={id}/></section><section className="glass form-card"><h3>Reconcile to broker</h3><p className="help">Differences create adjustment events; historical trades are not rewritten.</p><ReconcileForm id={id} expected={latestValue?Number(latestValue.value):null}/></section></div>
  <div className="detail-grid"><section className="card"><h3>Contribution history</h3>{contributions.length?contributions.map((c:any,i:number)=><div className="why-row" key={i}><span>{new Date(c.occurred_at).toLocaleString("en-GB")}</span><b>{new Intl.NumberFormat("en-GB",{style:"currency",currency:s.currency}).format(Number(c.cash_amount))}</b></div>):<p className="help">No contributions recorded.</p>}</section><section className="card"><h3>Reconciliation history</h3>{reconciliations.length?reconciliations.map((r:any,i:number)=><div className="why-row" key={i}><span>{new Date(r.occurred_at).toLocaleDateString("en-GB")} · {r.reason??"Adjustment"}</span><b>{Number(r.difference).toFixed(2)}</b></div>):<p className="help">No reconciliations yet.</p>}</section></div>
  <section className="card" style={{marginTop:16}}><div className="eyebrow">Rules & disclosure</div><h3>Versioned strategy definition</h3><p>{s.disclosure}</p><details><summary>Show configured engine inputs</summary><pre style={{whiteSpace:"pre-wrap",color:"var(--muted)"}}>{JSON.stringify(s.config,null,2)}</pre></details></section></>;
}
