import Link from "next/link";
import { requireUser } from "@/lib/session";
import { listUserStrategies } from "@/lib/strategy-service";
import { sql } from "@/lib/db";

export default async function OverviewPage(){
  const user=await requireUser();
  const strategies=await listUserStrategies(user.id);
  const actions=await sql.unsafe("SELECT a.id,a.title,a.instruction,a.due_at,a.confidence,i.name AS instance_name FROM actions a JOIN strategy_instances i ON i.id=a.strategy_instance_id WHERE i.user_id=$1 AND a.status IN ('CALCULATED','NOTIFIED','ACKNOWLEDGED') AND a.action_type<>'NO_ACTION' ORDER BY COALESCE(a.due_at,a.created_at),a.created_at LIMIT 12",[user.id]);
  const values=await sql.unsafe("SELECT ps.strategy_instance_id,ps.value FROM performance_series ps JOIN strategy_instances i ON i.id=ps.strategy_instance_id WHERE i.user_id=$1 AND ps.series_type='USER_VALUE' AND ps.date=(SELECT max(p2.date) FROM performance_series p2 WHERE p2.strategy_instance_id=ps.strategy_instance_id AND p2.series_type='USER_VALUE')",[user.id]);
  const contributions=await sql.unsafe("SELECT COALESCE(sum(l.cash_amount),0) AS total FROM ledger_events l JOIN strategy_instances i ON i.id=l.strategy_instance_id WHERE i.user_id=$1 AND l.event_type='CONTRIBUTION'",[user.id]);
  const knownValue=values.length?values.reduce((sum,r)=>sum+Number(r.value),0):null;
  return <><div className="page-title"><div><div className="eyebrow">Overview</div><h1>Where am I?</h1><p>Your configured strategies, one action queue.</p></div><Link className="button primary" href="/app/strategies/new">Add strategy</Link></div>
  <div className="metrics"><div className="glass metric"><small>Total tracked value</small><strong>{knownValue==null?"—":new Intl.NumberFormat("en-GB",{style:"currency",currency:user.baseCurrency,maximumFractionDigits:0}).format(knownValue)}</strong></div><div className="glass metric"><small>Total contributions</small><strong>{new Intl.NumberFormat("en-GB",{style:"currency",currency:user.baseCurrency,maximumFractionDigits:0}).format(Number(contributions[0]?.total??0))}</strong></div><div className="glass metric"><small>Active strategies</small><strong>{strategies.filter((s:any)=>s.status==="ACTIVE").length}</strong></div><div className="glass metric"><small>Actions requiring attention</small><strong>{actions.length}</strong></div></div>
  <section className="glass action-queue"><div className="section-head"><div><h2>Global action queue</h2><p>What needs attention across every active strategy.</p></div></div>{actions.length?actions.map((a:any)=><div className="action-row" key={a.id}><div className="action-time">{a.due_at?new Date(a.due_at).toLocaleDateString("en-GB",{day:"2-digit",month:"short"}):"NOW"}</div><div><div className="action-title">{a.instance_name}</div><div className="action-sub">{a.title} · {a.instruction}</div></div><span className={"pill "+(a.confidence==="HIGH"?"good":"warn")}>{a.confidence}</span></div>):<div className="empty">Everything is on track. No outstanding strategy actions.</div>}</section>
  <div className="strategy-grid">{strategies.map((s:any)=><Link href={"/app/strategies/"+s.id} className="card strategy-card" key={s.id}><div className={"pill "+(s.health_status==="HEALTHY"?"good":"warn")}>{s.health_status.replaceAll("_"," ")}</div><h3 style={{marginTop:15}}>{s.name}</h3><p>{s.strategy_name} · {s.wrapper} · v{s.version}</p><div className="strategy-meta"><span className="pill">{s.status}</span><span className="pill">{s.currency}</span></div></Link>)}</div>
  {!strategies.length&&<div className="empty" style={{marginTop:16}}>No strategies yet. <Link href="/app/strategies/new">Add your first strategy.</Link></div>}</>;
}
